export const FETCH_BATMAN_SHOWS_PENDING = 'FETCH_BATMAN_SHOWS_PENDING';
export const FETCH_BATMAN_SHOWS_FULFILLED = 'FETCH_BATMAN_SHOWS_FULFILLED';
export const FETCH_BATMAN_SHOWS_REJECTED = 'FETCH_BATMAN_SHOWS_REJECTED';

export const FETCH_BATMAN_SHOW_PENDING = 'FETCH_BATMAN_SHOW_PENDING';
export const FETCH_BATMAN_SHOW_FULFILLED = 'FETCH_BATMAN_SHOW_FULFILLED';
export const FETCH_BATMAN_SHOW_REJECTED = 'FETCH_BATMAN_SHOW_REJECTED';
